AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  learn go lambda api

Globals:
  Function:
    Timeout: 30

Resources:
  ESIndexMaker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: lambda-go-api
      Runtime: go1.x
      AutoPublishAlias: live